### ISSUE TITLE
Add symfony/debug in composer.json

### ISSUE THREAD

**Issue by karstennilsen** [TheDragonCode/notify-exceptions#13]
Error: Class 'Symfony\Component\Debug\Exception\FlattenException' not found in /vendor/andrey-helldar/notify-exceptions/src/Services/ExceptionHandler.php:72

It's fixed by adding symfony/debug in composer.json.

**Comment by andrey-helldar** [comment]
Fixed in version [3.2.2](https://github.com/andrey-helldar/notify-exceptions/releases/tag/v3.2.2).

Thank you!
