### ISSUE TITLE
FlattenExceptions excpects an Exception but get's an Error

### ISSUE THREAD

**Issue by karstennilsen** [TheDragonCode/notify-exceptions#14]
Hi,

For most exceptions Notifyex works but for some errors I get the following:

Exception thrown in Helldar\Notifex\Services\NotifyException::sendEmail when capturing an exception
TypeError: Argument 1 passed to Symfony\Component\Debug\Exception\FlattenException::create() must be an instance of Exception, instance of Error given, called in /vendor/andrey-helldar/notify-exceptions/src/Services/ExceptionHandler.php on line 72 and defined in /vendor/symfony/debug/Exception/FlattenException.php:42

Am I doing something wrong or is this a bug?

Karsten

**Comment by andrey-helldar** [comment]
Sounds like a bug. I'll check soon.

Can you provide the code that causes this error?

**Comment by karstennilsen** [comment]
I referenced a non existing class in my controller.
This gives you an Error - Class 'App\Http\Controllers\Input' not found, which it fails to mail.

`$test = Input::test;`

**Comment by andrey-helldar** [comment]
Fixed in version [3.2.3](https://github.com/andrey-helldar/notify-exceptions/releases/tag/v3.2.3).

Thank you!

![image](https://user-images.githubusercontent.com/10347617/104287842-10fadb00-54c8-11eb-9f21-25e666062c9c.png)
